--删除表，选择执行，没有以下表就不要运行这些删除表的语句
DROP TABLE HOUSE_PICTURE;
DROP TABLE HOUSE;
DROP TABLE STREET;
DROP TABLE DISTRICT;
DROP TABLE HOUSE_TYPE;
DROP TABLE HOUSE_USER;

--删除序列，选择执行，没有以下序列就不要运行这些删除序列的语句
DROP SEQUENCE HOUSE_USER_ID;
DROP SEQUENCE DISTRICT_ID;
DROP SEQUENCE HOUSE_ID;
DROP SEQUENCE STREET_ID;
DROP SEQUENCE HOUSE_TYPE_ID;
DROP SEQUENCE HOUSE_PICTURE_ID;


--创建表
-- Create table
CREATE TABLE HOUSE_USER
(
  ID        NUMBER(9) NOT NULL,
  USERNAME  VARCHAR2(50),
  PASSWORD  VARCHAR2(50),
  TELEPHONE VARCHAR2(15),
  REALNAME  VARCHAR2(50),
  ISADMIN   VARCHAR2(5)
);
ALTER TABLE HOUSE_USER
ADD CONSTRAINT PRI_HOUSE_USER PRIMARY KEY (ID)
  USING INDEX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
    (
  INITIAL 64K
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
    );


CREATE TABLE HOUSE_TYPE
(
  ID   NUMBER(9)    NOT NULL,
  NAME VARCHAR2(50) NOT NULL
);
ALTER TABLE HOUSE_TYPE
ADD CONSTRAINT PRI_HOUSE_TYPE PRIMARY KEY (ID)
  USING INDEX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
    (
  INITIAL 64K
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
    );

CREATE TABLE DISTRICT
(
  ID   NUMBER(9)    NOT NULL,
  NAME VARCHAR2(50) NOT NULL
);
ALTER TABLE DISTRICT
ADD CONSTRAINT PRI_DISTRICT PRIMARY KEY (ID)
  USING INDEX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
    (
  INITIAL 64K
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
    );

CREATE TABLE STREET
(
  ID          NUMBER(9) NOT NULL,
  NAME        VARCHAR2(50),
  DISTRICT_ID NUMBER(9)
);
ALTER TABLE STREET
ADD CONSTRAINT PRI_STREET PRIMARY KEY (ID)
  USING INDEX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
    (
  INITIAL 64K
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
    );
ALTER TABLE STREET
ADD CONSTRAINT STREET_REF_DISTRICT FOREIGN KEY (DISTRICT_ID)
REFERENCES DISTRICT (ID);

CREATE TABLE HOUSE
(
  ID          NUMBER(9) NOT NULL,
  USER_ID     NUMBER(9),
  TYPE_ID     NUMBER(9),
  TITLE       VARCHAR2(50),
  DESCRIPTION VARCHAR2(2000),
  PRICE       FLOAT,
  PUBDATE     DATE,
  ADDDATE     DATE,
  FLOORAGE    FLOAT,
  CONTACT     VARCHAR2(100),
  STREET_ID   NUMBER(9)
);
ALTER TABLE HOUSE
ADD CONSTRAINT PRI_HOUSE PRIMARY KEY (ID)
  USING INDEX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
    (
  INITIAL 64K
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
    );
ALTER TABLE HOUSE
ADD CONSTRAINT HOUSE_REF_HOUSE_TYPE FOREIGN KEY (TYPE_ID)
REFERENCES HOUSE_TYPE (ID);
ALTER TABLE HOUSE
ADD CONSTRAINT HOUSE_REF_HOUSE_USER FOREIGN KEY (USER_ID)
REFERENCES HOUSE_USER (ID);
ALTER TABLE HOUSE
ADD CONSTRAINT HOUSE_REF_STREET FOREIGN KEY (STREET_ID)
REFERENCES STREET (ID);


CREATE TABLE HOUSE_PICTURE
(
  ID       NUMBER(9) NOT NULL,
  HOUSE_ID NUMBER(9),
  TITLE    VARCHAR2(50),
  URL      VARCHAR2(500)
);
ALTER TABLE HOUSE_PICTURE
ADD CONSTRAINT PRI_HOUSE_PICTURE PRIMARY KEY (ID)
  USING INDEX
  PCTFREE 10
  INITRANS 2
  MAXTRANS 255
  STORAGE
    (
  INITIAL 64K
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
    );
ALTER TABLE HOUSE_PICTURE
ADD CONSTRAINT HOUSE_PICTURE_REF_HOUSE FOREIGN KEY (HOUSE_ID)
REFERENCES HOUSE (ID);


--创建序列
CREATE SEQUENCE HOUSE_USER_ID INCREMENT BY 1 START WITH 10;
CREATE SEQUENCE DISTRICT_ID INCREMENT BY 1 START WITH 10;
CREATE SEQUENCE HOUSE_ID INCREMENT BY 1 START WITH 10;
CREATE SEQUENCE STREET_ID INCREMENT BY 1 START WITH 10;
CREATE SEQUENCE HOUSE_TYPE_ID INCREMENT BY 1 START WITH 10;
CREATE SEQUENCE HOUSE_PICTURE_ID INCREMENT BY 1 START WITH 10;

--添加测试数据
INSERT INTO HOUSE_USER VALUES (1, 'accp', '111111', '13888888888', 'accp', 'n');
INSERT INTO HOUSE_USER VALUES (2, 'jbit', '111111', '13888888888', 'jbit', 'n');
INSERT INTO HOUSE_USER
VALUES (3, 'admin', '111111', '13888888888', 'admin', 'y');
COMMIT;

INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (1, '一室一厅');
INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (2, '一室两厅');
INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (3, '两室一厅');
INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (4, '两室两厅');
INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (5, '三室一厅');
INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (6, '三室两厅');
INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (7, '四室一厅');
INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (8, '四室两厅');
INSERT INTO HOUSE_TYPE (ID, NAME) VALUES (9, '四十三厅');
COMMIT;

INSERT INTO DISTRICT (ID, NAME) VALUES (1, '东城');
INSERT INTO DISTRICT (ID, NAME) VALUES (2, '西城');
INSERT INTO DISTRICT (ID, NAME) VALUES (3, '石景山');
INSERT INTO DISTRICT (ID, NAME) VALUES (4, '朝阳');
INSERT INTO DISTRICT (ID, NAME) VALUES (5, '丰台');
INSERT INTO DISTRICT (ID, NAME) VALUES (6, '海淀');
COMMIT;

INSERT INTO STREET (ID, NAME, DISTRICT_ID) VALUES (1, '知春路', 4);
INSERT INTO STREET (ID, NAME, DISTRICT_ID) VALUES (2, '中关村大街', 4);
INSERT INTO STREET (ID, NAME, DISTRICT_ID) VALUES (3, '学院路', 4);
INSERT INTO STREET (ID, NAME, DISTRICT_ID) VALUES (4, '朝阳路', 6);
COMMIT;

INSERT INTO HOUSE VALUES (1, 3, 1, '好房出租', '精装好房，不看后悔', 500,
                          to_date('2012-02-02 13:02:40',
                                  'yyyy-mm-dd hh24:mi:ss'),
                          to_date('2012-02-02 13:02:40',
                                  'yyyy-mm-dd hh24:mi:ss'), 60.5, '13496659878',
                          1);
INSERT INTO HOUSE_PICTURE VALUES (1, 1, '', '');
COMMIT;